### ISSUE TITLE
gmusicbrowser doesn't start anymore

### ISSUE THREAD

**Issue by jplatte** [squentin/gmusicbrowser#102]
Since a few weeks, gmusicbrowser doesn't start anymore on my PC. I just updated it to git master today and was unfortunately it still doesn't work. I don't think it's gmusicbrowser's fault, that's why I thought it might fix itself with an update of something else. Anyway, here is what I get when I try to run it:

    $ gmusicbrowser 
    Found orphaned fifo '/home/jonas/.config/gmusicbrowser/gmusicbrowser.fifo' : previous session wasn't closed properly
    /usr/bin/perl: symbol lookup error: /usr/lib/perl5/vendor_perl/auto/Glib/Object/Introspection/Introspection.so: undefined symbol: Perl_xs_apiversion_bootcheck

**Comment by squentin** [comment]
Yes, it's not a gmb issue.
It seems you have to re-install perl-glib-object-introspection : http://forum.gmusicbrowser.org/index.php?topic=885.0

**Comment by jplatte** [comment]
Reinstalling perl-glib-object-introspection worked, thanks! :)
