### ISSUE TITLE
mpv back end detection does not work on non version numbered release

### ISSUE THREAD

**Issue by zyphrus** [squentin/gmusicbrowser#105]
I have been using the mpv back end for a while and after an update to mpv, gmusicbrowser
does not show it as a valid back end anymore.

After some digging I found out that the version number string changed from
`mpv 0.9.2 (C) 2000-2015 mpv/MPlayer/mplayer2 projects` to `mpv git-f1778d1 (C) 2000-2015 mpv/MPlayer/mplayer2 projects`

As a temporary fix I added the following to my local copy

```perl
$ok = $output=~m/mpv\s*git/i ? 1 : $ok;
```
to [gmusicbrowser_mpv.pm's check_version](https://github.com/squentin/gmusicbrowser/blob/master/gmusicbrowser_mpv.pm#L48) function which gets everything working again but is probably not the best solution.

gmusicbrowser version: v1.1.15
OS: Arch Linux

**Comment by squentin** [comment]
Thanks, I'll fix it
