### ISSUE TITLE
Support freeform tag name entry in the filter editor

### ISSUE THREAD

**Issue by RomanHargrave** [squentin/gmusicbrowser#108]
I noticed that the filter editor currently sports a dropdown list of predefined fields on which to filter.

I would like to filter for tracks without replaygain tags; however, this specific set of tags is not part of the list. It would be nice if I were able to enter a specific tag name, _or_ select from predefined tags. Perhaps a drop-down _text field_ would be best suited for this purpose?

**Comment by squentin** [comment]
They are there, just under the names track_gain/track_peak/album_gain/album_peak.
I'm not sure about a text field, but I should probably categorize them like in the preferences/fields tab, they would then be under "replaygain".

Also you can just type, for example "track_gain=", in the search field, nothing after = means undefined/false. Though of course there is currently no field completion there, it's not easy to do it properly as a partial string can be a field name or a search pattern.
