### ISSUE TITLE
Launchpad build failed

### ISSUE THREAD

**Issue by aboettger** [squentin/gmusicbrowser#112]
https://code.launchpad.net/~andreas-boettger/gmusicbrowser/master

mkdir -p locale/es/LC_MESSAGES/
msgfmt --statistics -c -o locale/es/LC_MESSAGES/gmusicbrowser.mo po/es.po
po/es.po:6502: a format specification for argument 'filename' doesn't exist in 'msgstr'
msgfmt: found 1 fatal error
1548 translated messages, 81 untranslated messages.
make[1]: *** [locale/es/LC_MESSAGES/gmusicbrowser.mo] Error 1
Makefile:40: recipe for target 'locale/es/LC_MESSAGES/gmusicbrowser.mo' failed
make[1]: Leaving directory '/«BUILDDIR»/gmusicbrowser-1.1.15+1402~ubuntu15.10.1'
make: *** [install] Error 2
debian/rules:16: recipe for target 'install' failed
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2

**Comment by squentin** [comment]
fixed by d809521274, thanks
