### ISSUE TITLE
Dropping an album onto queue does not preserve ordering

### ISSUE THREAD

**Issue by viktordick** [squentin/gmusicbrowser#119]
If I use drag and drop to put an album into the queue, I would expect that the tracks are added in the order of their track number. Instead, the order is something different, not sure what. It seems to be reproducible, though.
A similar problem occurs if I select multiple songs and hit the shortcut for "Insert selected songs at the top of the queue". Sometimes the ordering seems to be the same as that in the library view, but sometimes it is not.

**Comment by squentin** [comment]
They are sorted using the current "play order", which can be shuffle or weighted random. It could be made configurable if enough people wants it.

**Comment by viktordick** [comment]
I tried to change the settings under 'play order', and now it seems to
work. The weird thing is, the setting is now exactly as it was at the
beginning ("Repeat" and "Artist, Album, Disc, Track").

**Comment by viktordick** [comment]
I guess I'll close the issue until I or someone else can reproduce it again.
