### ISSUE TITLE
Any possibility to remove the "Clean playlist" button?

### ISSUE THREAD

**Issue by Naereen** [squentin/gmusicbrowser#127]
Hi,
First, thanks a lot for your project, it is a wonderful music collection player :musical_score: !
I really love it :clap: !

Now, here is my question, I looked in the documentation and in the GUI, but found nothing:
is there any way to customize the GUI to **remove** (or add a confirmation button) to the "Clean" playlist button (in the view "with browser and playlist") ?
I am regularly annoyed to spend some time in creating a nice playlist, them shuffling it before going back to work, but... click the wrong button and erase it.

Thanks in advance!

**Comment by squentin** [comment]
There is no layout named "with browser and playlist" in the official repository, nor is there a layout that use the EmptyList widget that seems to be your problem. So I guess you are using a layout from someone else.

Anyway, you just need to find the layout file (either in ~/.config/gmusicbrowser/layouts/ or /usr/share/gmusicbrowser/layouts/) and remove the word "EmptyList" from it.

Layout files are text files that can contain multiple layouts, each one begins with a name between brackets "[Some layout name]". Let me know if you need help editing the layout.

**Comment by Naereen** [comment]
Thanks.

Sorry, the name of the layout was "with browser & queue" (I translated in English wrongly). My gmusicbrowser is in French.

I did not find any "EmptyList" word in the layout (in the whole /usr/share/gmusicbrowser/ folder, only ``gmusicbrowser_layout.pm`` uses this word).
Anyway, I edited ``gmusicbrowser_list.pm`` and ``gmusicbrowser_layout.pm``, to be able to switch the "Shuffle" and "Clear" buttons, and that's enough for not messing up with it :) (shuffle on the left, clear on the right).
On restart nothing has changed, I will try to reboot to see if it changes anything.

**Comment by squentin** [comment]
I see, I didn't think about this being the queue.

You can edit this line in gmusicbrowser_list.pm :
  `$self->pack_start($self->{$_},FALSE,FALSE,2)` for qw/btop bup bdown bbot brm bclear bshuffle/;
to either remove the word "bclear" or change the order of the words between the // to change the order of the buttons.

I'll think about adding an option to disable some buttons or change their order.

**Comment by Naereen** [comment]
OK, it was my second guess (as I don't know perl, I thought the order here might have been not important). Thanks.

I don't think it is worth spending time on an option to reorder the button, but if you can do this quickly sure :+1: !

Thanks and :clap: again!

**Comment by Naereen** [comment]
Just for your information, your suggestion worked fine, exactly as I wanted:
![shuffle_button_on_the_left](https://cloud.githubusercontent.com/assets/11994719/13215797/4eb13dea-d958-11e5-9a5f-7f0899761afe.png)

(the "Shuffle" button is far away from the "Clear queue" one)

**Comment by Naereen** [comment]
Thanks again, I think this issue can be closed.
