### ISSUE TITLE
gmusicbrowser exits with Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Spike29** [squentin/gmusicbrowser#131]
gmusicbrowser works fine, but I recently started it in a console and found out that most of the time, when you close the application, it exits with a segfault.

Here's some console output:

_[yannick@Endeavour:~]$ gmusicbrowser
Reading saved tags in /home/yannick/.config/gmusicbrowser/gmbrc ...
Reading saved tags in /home/yannick/.config/gmusicbrowser/gmbrc ... done
no lyrics found in /home/yannick/Musique/Musique/The Clash/The Clash/01 Janie Jones.mp3
lyrics : loading http://letras.terra.com.br/winamp.php?musica=janie%20jones&artista=the%20clash
Writing tags in /home/yannick/.config/gmusicbrowser/gmbrc ...
Writing tags in /home/yannick/.config/gmusicbrowser/gmbrc ... done
Erreur de segmentation (core dumped)_

**Comment by RomanHargrave** [comment]
That's strange, considering this is a perl application.

What version of perl do you have installed?

**Comment by Spike29** [comment]
I use Perl 5.22.2 (and gtk2-perl 1.2498).

**Comment by chinarulezzz** [comment]
I have same.

1. Perl 5.22.2 (gtk2-perl 1.2498);
2. Perl 5.18.1 (gtk2-perl 1.248)

In both cases gmusicbrowser is from master branch.

**Comment by RomanHargrave** [comment]
Not running off master right now, but I was running just fine on my laptop which uses 5.22.

**Comment by nicolas-raoul** [comment]
Same problem here, gmusicbrowser never quits properly, it always crashes. Exemple:
```
gmusicbrowser[21610]: segfault at c ip 00007fad6f9e7820 sp 00007fffb02dd6c0 error 4 in libgobject-2.0.so.0.4800.1[7fad6f9c6000+52000]
```

**Comment by bor** [comment]
Same issue.
gmb save state and remove fifo fine, but after
```
...
rt_sigaction(SIGABRT, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGCHLD, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGIO, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGSYS, NULL, {SIG_DFL, [], 0}, 8) = 0
munmap(0x7fbba0541000, 270336)          = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x9} ---
+++ killed by SIGSEGV +++
Segmentation fault
```

**Comment by dicktyr** [comment]
I also see this issue
both for SIGTERM and for the "Quit" menu item
however the following command does not segfault

`gmusicbrowser -cmd Quit`

**Comment by Vladimyr0** [comment]
for me, it happens sometimes. 
more time of working after start increases probability of the crash.
ubuntu 18.04 64-bit, perl v5.26.1

**Comment by bor** [comment]
Today I tried the new 1.1.16 version and looks like the bug was disappeared.
I believe that 9bd728265fc89c87beb324d0fe07bd8e2d106ec2 commit does the fix.
