### ISSUE TITLE
"Search for a picture on the internet" not working

### ISSUE THREAD

**Issue by nashley** [squentin/gmusicbrowser#136]
Most of the image search engines don't work. In fact, I was only able to get yahoo working.
Am I alone with this problem?

Also, it appears that searching Google by any means except that which they provide or have given permission for is against their [TOS](https://www.google.com/intl/en/policies/terms/):

> "... don’t interfere with our Services or try to access them using a method other than the interface and the instructions that we provide."

Google has an [Image Search API](https://developers.google.com/image-search/v1/devguide#top_of_page), but it's sadly deprecated (and limited to 100 queries a day). Instead, they state that their [Custom Search API](https://developers.google.com/custom-search/json-api/v1/overview) should be used, but it has suffers from the same query limit and would require an account to be created:

> For CSE users, the API provides 100 search queries per day for free. If you need more, you may sign up for billing in the Developers Console. Additional requests cost $5 per 1000 queries, up to 10k queries per day.

Unless every user made their own custom search account, I don't think this would work very well.
There's a similar model for [Bing's Image search](http://www.bing.com/developers/s/apibasics.html).

It sadly doesn't look like [DuckDuckGo's API](https://duckduckgo.com/api) supports searching for images past their "Instant Answer" feature.

Potential services:
- [Discogs](https://www.discogs.com/developers/#page:images)
  - Needs to be updated to use authentication
- [SlothRadio](http://covers.slothradio.com/)
  - Implemented, but looks like it needs to be fixed
- Continue using Google/Bing/DDG even though they're not supported
- Last.fm (for artists only)
  - Not working for me, but the service should be fine

**Comment by nashley** [comment]
Perhaps [Amazon's service](https://affiliate-program.amazon.com/gp/advertising/api/detail/main.html) could be used?
See [this writeup](http://www.codeproject.com/Articles/36001/Using-Public-Web-Services-to-get-Information-about) by the maker of "Music Explorer".

**Comment by nashley** [comment]
Actually, I think using [archive.org's api](https://archive.org/help/json.php) would be best. I'll look at implementing it (and maybe amazon's as well).

**Comment by dagobertstyle** [comment]
Now, all of the image search engines don't work....

**Comment by squentin** [comment]
I've just updated the plugin, google, bing and ddg should work again. Yahoo still worked. Though of course I'm talking about the git version as gmb's last released version is ancient. I'll probably make a new release soon.
