### ISSUE TITLE
Gmusicbrowser cannot use Gstreamer 1.10.3

### ISSUE THREAD

**Issue by Photon89** [squentin/gmusicbrowser#139]
The Gstreamer 0.10 plugins have been recently kicked out of the Arch Linux repositories, now there are packages versioned 1.10.3. It looks like Gmusicbrowser cannot use this version of Gstreamer.

**Comment by jplatte** [comment]
Gmusicbrowser is compatible with gstreamer1.x, you just need perl-glib-object-introspection. It seems like this is not made fully clear in the optional deps of the non-git package.

**Comment by Photon89** [comment]
Thanks, you are right!
