### ISSUE TITLE
Search-as-you-type causes crash

### ISSUE THREAD

**Issue by Vladimir-csp** [squentin/gmusicbrowser#141]
Debian testing, gmusicbrowser 1.1.15.
Invoking search in any list crashes the program.

In main list:
```
invalid iter -- stamp -1875915568 does not match requested 94319900871888 at /usr/bin/../share/gmusicbrowser/gmusicbrowser_list.pm line 1491, <GEN23> line 51.
Segmentation fault
```
In search list:
```
invalid iter -- stamp -681055048 does not match requested 94140707105976 at /usr/bin/../share/gmusicbrowser/gmusicbrowser_list.pm line 1491.
Segmentation fault
```
In queue:
```
invalid iter -- stamp -1328951024 does not match requested 94457886789904 at /usr/bin/../share/gmusicbrowser/gmusicbrowser_list.pm line 1491, <GEN0> line 78.
Segmentation fault
```

**Comment by chinarulezzz** [comment]
what versions of the software/dependencies you have? I also met with this problem in other distro's.

My 'ok' configuration:

```
- gmusicbrowser == git
- gtk == 2.24.31
- perl-gtk2 == 1.24991
- pango == 1.40.4
- perl-pango == 1.2272
- cairo == 1.15.4
- perl-cairo == 1.106
- glib == 2.50.3
- perl-glib == 1.324
```

**Comment by Vladimir-csp** [comment]
```
libgtk2.0-common                  2.24.31-2
libgtk2-perl                      2:1.2499-1
libpango-1.0-0:amd64              1.40.4-1
libcairo-perl                     1.106-1+b2
libcairo2:amd64                   1.14.8-1  
libglib2.0-0:amd64                2.50.3-1
libglib-perl                      3:1.324-1
```

**Comment by chinarulezzz** [comment]
The packages I've compiled with these options:
- gtk2
```no opts, default```
- perl-gtk2
```
        perl Makefile.PL                \
                --without-gdkimlib      \
                --without-gnome         \
                --without-gnomeprint    \
                --without-glade
```
- pango
```no opts, default```
- perl-pango
```no opts, default```
- cairo
```
        ./configure --prefix=/usr \
                --enable-xcb=yes \
                --enable-ps \
                --enable-pdf \
                --disable-gtk-doc \
                --enable-tee=yes
```
- perl-cairo
```no opts, default```
- glib
```
    ./configure --prefix=/usr \
                --disable-man \
                --with-pcre=system
```
- perl-glib
```no opts, default```

And all works fine.

**Comment by Vladimir-csp** [comment]
There seem to be a lot of build options in gtk2 packages alone. I'll report a debian bug.

**Comment by jspricke** [comment]
I compiled everything from source, as @chinarulezzz proposed¹ in a minimal Debian unstable chroot and was still able to reproduce the bug. Here are the steps to reproduce them, as @Vladimir-csp wrote in the Debian bug:

> Reproduction steps from fresh state: 
> - add a library with at least one track
> - switch player window layout to "with lists"
> - try typing in main list

@chinarulezzz are you sure this works for you? Can you come up with a chroot/VM/Vagrant file to reproduce your system, so we can have a look which library produces the error? Otherwise I can send my log, if you want to reproduce it yourself.

¹ except perl-gtk2 == 1.24991 where I was only able to find 1.2499, I guess it's a typo.

**Comment by OBedford** [comment]
I'm facing the same bug on (X)Ubuntu 16.04. Everything installed from the default packages.
Is there a solution available?
TIA, Oliver

**Comment by jspricke** [comment]
This has been fixed in: https://github.com/squentin/gmusicbrowser/commit/d26f6adea435104382adc24a975e2a52b7213ec5

**Comment by OBedford** [comment]
I've downloaded the gmusicbrowser-master.zip and installed from there. Problem gone.
Thanks!
