### ISSUE TITLE
wav & aiff 

### ISSUE THREAD

**Issue by mendomusic** [squentin/gmusicbrowser#144]
please add capability to play wav, aif, aiff files

**Comment by RomanHargrave** [comment]
Using the mpv backend (and probably gstreamer), it can as far as I can tell.

**Comment by squentin** [comment]
In case you still care, you can now (git version, in both master (gtk3) and v1.1.x (gtk2) branches) add any format recognized by gstreamer or mediainfo, though they are added in read-only mode: any change to the metadata you make is only changed within gmb. It is disabled by default you need to enable extensions in Settings->Library->"Select which file types are added".
