### ISSUE TITLE
mplayer called with unknown options

### ISSUE THREAD

**Issue by moschroe** [squentin/gmusicbrowser#145]
Hi,

love gmusicbrowser, just the right tool for me. But since the last update of perl, the legacy gstreamer packages are no longer compatible (had to remove them), so no more gstreamer backend.

In preferences, I switched to mplayer, as this tool plays just about anything. But I keep getting a "Playing error".
- Arch Linux
- gmusicbrowser 1.1.15
- MPlayer SVN-r37916

I copied the details from the error dialog (great choice to put those there) and executed the same command in my terminal.
```
$ /usr/bin/mplayer -nocache -idle -slave -novideo -nolirc -hr-mp3-seek -msglevel \
all=1:statusline=5:global=6 --input=nodefault-bindings:conf=/dev/null -softvol -volume 0 \
--softvol-max=100 -ao pulse 'x.flac'

Unknown option on the command line: --input=nodefault-bindings:conf=/dev/null
Error parsing option on the command line: --input=nodefault-bindings:conf=/dev/null
get_path('codecs.conf') -> '/home/x/.mplayer/codecs.conf'
get_path('fonts') -> '/home/x/.mplayer/fonts'
```

I then removed one offending option after the other until mplayer ran.
- `--input=nodefault-bindings:conf=/dev/null`
- `--softvol-max=100`

```
$ /usr/bin/mplayer -nocache -idle -slave -novideo -nolirc -hr-mp3-seek -msglevel \
all=1:statusline=5:global=6 -softvol -volume 0 -ao pulse 'x.flac'

get_path('codecs.conf') -> '/home/x/.mplayer/codecs.conf'
get_path('fonts') -> '/home/x/.mplayer/fonts'
get_path('input.conf') -> '/home/x/.mplayer/input.conf'
get_path('x.flac.conf') -> '/home/x/.mplayer/x.flac.conf'
get_path('sub/') -> '/home/x/.mplayer/sub/'
get_path('sub/') -> '/home/x/.mplayer/sub/'
[Mixer] No hardware mixing, inserting volume filter.
^C   0.9 (00.8) of 285.0 (04:45.0)  0.4%
MPlayer interrupted by signal 2 in module: play_audio
```

I downloaded the last two releases from mplayerhq.hu (1.2.1 & 1.3.0), compiled them, tested the same command against them and got the same response (`Unknown option...`).

The arguments are part of the internally generated command and cannot be set by the user. I suspect that mplayer changed its behaviour at some point and since then, no-one ever used gmusicbrowser with it.

Are those arguments important for older versions? Can they simply be removed?

**Comment by ethus3h** [comment]
I don't know about the mplayer issue (I don't use the mplayer backend), but using the Glib-Object-Introspection Perl module (using the Gentoo package) the gstreamer backend works fine for me with modern gstreamer...

**Comment by squentin** [comment]
Which gstreamer version are you talking about ? gstreamer-1.x should work with Glib-Object-Introspection package and gstreamer-1.x introspection data as ethus3h said.

Also you can try mpv.

The "--input=nodefault-bindings:conf=/dev/null" option is to avoid strange interaction with mplayer options that you might have set outside of gmb.

I've just tried mplayer 1.3.0 from ubuntu and it works fine, though I do get the same option error when trying the command line, I'll look into this.

**Comment by moschroe** [comment]
Sorry for the delay, finishing my master's thesis atm. I cannot find any packages with `pacman -Ss intro` that have a matching name and are not already installed.
```
extra/gobject-introspection 1.52.1-1 [installed]
    Introspection system for GObject-based libraries
extra/gobject-introspection-runtime 1.52.1-1 [installed]
    Introspection system for GObject-based libraries (runtime library)
extra/lua-lgi 0.9.1-1
    Lua bindings for gnome/gobject using gobject-introspection library
community/gir-to-d 0.11.0-1
    Create D bindings from GObject introspection files
community/pkgbuild-introspection 8-1
    Tools for generating .AURINFO files and PKGBUILD data extraction
community/ruby-gobject-introspection 3.1.6-1
    Ruby/GObjectIntrospection is a Ruby binding of GObjectIntrospection.
```

I am successfully using `mpv` as a workaround, that works fine so far.

What about changing the `mplayer` invocation? Detecting the version seems difficult since on Arch, they use an SVN revision, not a semantic version. Don't know about other distros, might impact portability.

**Comment by scott-tancock** [comment]
I can confirm this issue with mplayer SVN-r37916.  mplayer appears to have changed it's command line format from --long_option=value to -long_option value.  

```
$ uname -a:
Linux BLACK-BOX 4.13.5-1-ARCH #1 SMP PREEMPT Fri Oct 6 09:58:47 CEST 2017 x86_64 GNU/Linux
$ mplayer
MPlayer SVN-r37916 (C) 2000-2017 MPlayer Team
$ gmusicbrowser -v      
unknown option '-v'
gmusicbrowser v1.1.15 (c)2005-2015 Quentin Sculo
```
