### ISSUE TITLE
Remove the 'None' or 'No Label' row from lists of 'flag' field types

### ISSUE THREAD

**Issue by morgannunan** [squentin/gmusicbrowser#159]
Currently, if you're using a field like Themes, Styles, Labels, or a custom field that uses the 'flag' type, and you list this as a tab in your tree browser, you will get 'none' or 'no label' as an option.

There is also an 'All' row, and there's an option to remove this row. However, there is no option to remove 'None'. This is a problem because there's a good chance that 'none' is going to cover most of your collection. Let's say you have 5000 songs and you've tagged Styles for about 200. 'None' will list 4800 songs, making the histogram useless, and making the 'All' row useless because it includes 'None' or "No Label', and thus always shows the entire collection.

For these reasons, I think it would be good to either remove 'None', or give the user the option to remove it.

**Comment by squentin** [comment]
implemented in this commit 4fea67064d3e0714d308d2270c037642cf973492
