### ISSUE TITLE
Crash in v1.1.15 (Fedora 28)

### ISSUE THREAD

**Issue by vlisivka** [squentin/gmusicbrowser#162]
invalid iter -- stamp 820282280 does not match requested 94799338439592 at /usr/bin/../share/gmusicbrowser/gmusicbrowser_list.pm line 1491.
Segmentation fault 

Steps to reproduce:

Enter full screen mode using "Garage fullscreen" layout.
Select "Songs" panel.
Press '[' or ']'.

**Comment by squentin** [comment]
I've committed this patch d26f6adea435104382adc24a975e2a52b7213ec5 that should fix it (I fixed it a while ago, but didn't push it).
