### ISSUE TITLE
Is random function not very random?

### ISSUE THREAD

**Issue by gitut2007** [squentin/gmusicbrowser#166]
Hi, in the forum someone wrote: 
"random function is  not very random out of a 700 file playlist I seem to hear about 50 songs all the time"
you didn't deny it but proceeded with other recommendations, so i wonder if the random algorithm has improved since then.
If the random function is not too good, just simple Random could be replaced with Shuffle, but Weighted Random -which i think is unique to GMB- would require eg making a static playlist with repeated songs to replace it, but with more hassle...

**Comment by squentin** [comment]
Cleaning up issues a bit... Sorry for not replying sooner.

I'm pretty sure it's working fine, it's either a perception problem (it happens) or a misunderstanding of the weighed random parameters, which is perfectly understandable as the interface is rather complex.
By the way a shuffle mode is already available if you prefer.

Anyway, in case anyone wants to investigate the randomness, here are a few commands that could be useful:

```
gmusicbrowser -cmd 'RunPerlCode(open my$fh,">/tmp/draw"; for (1..100) { my ($ID)= $RandomMode->Draw(1); say $fh $ID; } close $fh)'

gmusicbrowser -cmd 'RunPerlCode(open my$fh,">/tmp/draw"; my %h; for (1..100) { my ($ID)= $RandomMode->Draw(1); $h{$ID}++; } say $fh "$h{$_} ".ReplaceFields($_,"%t by %a") for sort {$h{$a} <=> $h{$b}} keys %h; close $fh)'
```
Both will use the currently selected random mode, it will fail if no random mode is selected.
The first one will draw a song 100 times and will output their ID number in sequence.
The second one will draw a song 100 times and output a list of picked songs containing the number of times it was picked, followed by title and artist, all that sorted by number of times picked.
The output will be in /tmp/draw.
