### ISSUE TITLE
Suddenly crashing

### ISSUE THREAD

**Issue by angiioh** [squentin/gmusicbrowser#167]
I've used gmusicbrowser for over a year now and it's suddenly crashing when it tries to start playing a new song. I've tried it with multiple tracks (all successfully played before) from multiple albums. I also made sure it wasn't scanning or anything while it tries to play. It will play the track for about 2 seconds (track bar won't move, but I'll hear music) and then close the program.

Any ideas on how to fix this? This is my favorite music player on linux.

Thanks!

**Comment by squentin** [comment]
Can you run it from a terminal and see what it says when it crashes ?
(open a terminal and type "gmusicbrowser")

**Comment by angiioh** [comment]
Sure, just did that and it just says 'Killed.'

**Comment by squentin** [comment]
That's weird, 'Killed' is the message you get when the program is killed with "kill -9", that looks like something is killing it for some reason, I really don't know what it could be.

What you can do is try other options in the Settings->Audio dialog. If it is set on gstreamer, you can try another "output", or you can try mpv or mpg123/...

**Comment by angiioh** [comment]
Yeah, it's really strange. Some more details: when I start it, it will play the song that it was last playing fine. It will play the entire track and the track progress bar moves. Then it will try to play the next song in the queue or I'll switch it to another random track and it will play for around 5 seconds but the track progress bar doesn't move, then it will close. 

It doesn't allow me to choose mpv or mpg123. I switched from 'auto detect' under gstreamer to Alsa, openal, and Pulseaudio and it acted the same.

**Comment by squentin** [comment]
Maybe there is a clue in the system log.

You can install mpv (a very good video player) to enable the mpv option.

**Comment by angiioh** [comment]
I figured it out! A plugin (https://github.com/mklinga/gmusicbrowser-plugins/tree/master/lastfm_pcget) that I've been using for over a year was killing it for some reason. Thanks for trying to help me troubleshoot.
