### ISSUE TITLE
Progress "window" should be dialog

### ISSUE THREAD

**Issue by joeriexelmans** [squentin/gmusicbrowser#170]
gmusicbrowser 1.1.15 (distro package)
Ubuntu 19.10

Progress dialog is not a dialog.
Turning it into a dialog can help window managers to display it in a better way.
E.g. a tiling window manager may display it as "floating" by default instead of trying to fill the screen with it.

I don't know Perl, but I'm pretty sure this is the line where the dialog is created:
https://github.com/squentin/gmusicbrowser/blob/master/gmusicbrowser.pl#L7748

**Comment by squentin** [comment]
I don't use a tiling window manager, so I can't easily test it, but can you test this:
in /usr/share/gmusicbrower/layouts/main.layout search for the "Progress" layout and add the "Window=" line as below:
```
[Progress]
Window		= typehint=dialog
VBmain		= _VProgress(lastclose=1)
Title		= _"Progress"
```

**Comment by joeriexelmans** [comment]
Yes, this fixes it.
