### ISSUE TITLE
Feature Request: Flatpak Support.

### ISSUE THREAD

**Issue by BeatLink** [squentin/gmusicbrowser#173]
In the coming days, I will attempt to create a flatpak package and upload it to flathub, with your blessings ofcourse. This issue will be to document my progress, raise issues and discuss decisions that need to be made.

**Comment by BeatLink** [comment]
To start with, the app id will be "org.gmusicbrowser.gmusicbrowser". Let me know if that needs to be changed. 

The runtime will be GNOME

**Comment by BeatLink** [comment]
Ive already made an initial flatpak manifesto. It compiles, but if shows the following error

```
Can't locate Gtk2.pm in @INC (you may need to install the Gtk2 module) (@INC contains: /usr/lib/perl5/site_perl/5.30.0/x86_64-linux /usr/lib/perl5/site_perl/5.30.0 /usr/lib/perl5/vendor_perl/5.30.0/x86_64-linux /usr/lib/perl5/vendor_perl/5.30.0 /usr/lib/perl5/5.30.0/x86_64-linux /usr/lib/perl5/5.30.0) at /app/bin/gmusicbrowser line 25.
BEGIN failed--compilation aborted at /app/bin/gmusicbrowser line 25.
```

Im not sure how to include the gtk2.pm

Here's the repo with the added flatpak files.

https://github.com/BeatLink/gmusicbrowser

**Comment by BeatLink** [comment]
The bug has been solved earlier this morning and I'm making great progress! The build compiles successfully and i am now ready to perform the first test

**Comment by squentin** [comment]
I'm really not familiar with flatpack.
I haven't look at what you've done, but be aware that the latest official release is very old (sorry), so you should use the latest git version instead. The master branch is the gtk3 port, it is still in beta. If you want the gtk2 version you should use the branch v1.1.x which will probably only receive bugfixes.

**Comment by BeatLink** [comment]
ahh okay. Im currently building with the 1.1.x branch. Is the gtk3 port stable?

**Comment by BeatLink** [comment]
Also, dont sweat gmusicbrowser being old. It just goes to show how good the app is when it hasnt needed a major change in 5 years and still works great XD

**Comment by squentin** [comment]
The gtk3 port is stable but there are some small bugs, mainly sizing of elements in some layouts and some the icons are a mess though it's doesn't show too much, it's mostly small things and theming.
Also the SongList is slow when filling/removing lots of songs, which may not be fixable, but the SongTree is fast and can be made to look mostly like a regular SongList.
On the other hand some old plugins like webcontext work again as they don't need perl bindings for libraries just their introspection data.

**Comment by BeatLink** [comment]
ooh okay great! Im happy to report that the build is going great! The app will launch successfully now. All that is left to add is include the music playing command and dependencies to handle the different file formats. things like mpg123 and its flac and ogg counterparts

**Comment by BeatLink** [comment]
Once its all done and polished, ill upload it to [flathub.org](https://flathub.org)! With your blessings ofcourse

**Comment by BeatLink** [comment]
It works! Everything checks out. I will go ahead and submit the code to flathub

**Comment by BeatLink** [comment]
Slight snag with the build but im working on it. Baiscally, flatpak uses a special library folder to save data in (under /app) but gmusicbrowser has some hardcoded paths in the executable under /usr that makes the build break. I've created a simple pull request to fix it here:

https://github.com/squentin/gmusicbrowser/pull/175

Once thats approved, i can try the build again

**Comment by BeatLink** [comment]
Ive created a patch to bypass the executable issue. The flatpak build is now fully functional!

I will be submitting this build to flathub tonight. Only locales/translations and mpv arent working in this build according to gmb's console output

**Comment by BeatLink** [comment]
The flathub builds are failing due to not being able to find the appstream file. Renaming the file should do the trick. I've opened a PR here https://github.com/squentin/gmusicbrowser/pull/178

**Comment by BeatLink** [comment]
The flathub test build has completed successfully! Now waiting on flathub admins to finish their reviews and upload. 

You can check out the test build here:

**Comment by timnunes** [comment]
Installation doesn't show any errors, but `flatpak run org.gmusicbrowser.gmusicbrowser` gives an error:

`org.freedesktop.DBus.Error.AccessDenied: org.freedesktop.DBus.Error.AccessDenied`

**Comment by BeatLink** [comment]
Hmm, It should be working now after the latest build. Try uninstalling and reinstalling from the very latest build output by the bot

**Comment by BeatLink** [comment]
The appstream file isnt an issue, i was able to use an alternate name in the manifest itself

**Comment by timnunes** [comment]
Uninstalling and reinstalling worked. I'm certain I used the same build the first time, but maybe not. This time I used `flatpak install --user https://dl.flathub.org/build-repo/22363/org.gmusicbrowser.gmusicbrowser.flatpakref`.

**Comment by BeatLink** [comment]
hmm. Well each build produces a new flatpakref if im not mistaken. So it would always be best to grab the latest

**Comment by BeatLink** [comment]
:tada: gmusicbrowser is now officially on flathub! :tada:

https://flathub.org/apps/details/org.gmusicbrowser.gmusicbrowser

All thats left to do is to give you write access to the flathub repo (being tracked here https://github.com/flathub/org.gmusicbrowser.gmusicbrowser/issues/1) and merge this pull request so there is a backup of the recipes in the gmusicbrowser repo itself (being tracked here https://github.com/squentin/gmusicbrowser/pull/176)

I''ll keep this issue open until these last two things are done and then i'll close the issue but it works!

**Comment by yennor** [comment]
I've just wanted to install it to try it out. But flatpak wants to download more than 700MB of data therefore. WIth my current internet connection that would be over a day of downloading.
Does it really need the dependencies:
 org.gnome.Platform
 org.gnome.Platform.Locale       
? Aren't there some subdependencies you could use?
(I've never used flatpak before, so I really don't know if it is a stupid question or not ;-))

**Comment by BeatLink** [comment]
Yes, thats how flatpak works. Basically, the gnome platform is a rather large dependency, but its used by thousands of different flatpak apps so overall it ends up saving space in the end. Its probably big at first since its your first flatpak app. But if you installed another flatpak app depending on the gnome platform it would be small in comparison.
