### ISSUE TITLE
Openbsd / Can't locate Gtk3.pm

### ISSUE THREAD

**Issue by ralphee** [squentin/gmusicbrowser#183]
pls note I receive the following [error](http://ix.io/2u20) msg when launching gmusicbrowser in openbsd

**Comment by squentin** [comment]
The latest version in git uses gtk3. The error means it cannot find the Gtk3 perl library.
I don't much about openbsd, so I can't help much, a quick search lead me to http://ports.su/perl5 which doesn't have Gtk3, but does have Glib::Object::Introspection.

I don't know what is your level of knowledge in this area, so I don't know if this will help, but here goes:
gtk3 is a C library, gmusicbrowser is perl, it uses the perl library Glib::Object::Introspection to load a lot of C libraries using introspection data (typelib files), though in the case of gtk3 it still uses the introspection, but loads it via a small perl library called Gtk3 to make the many gtk3 functions a bit more perlish. Gtk3.pm is a simple pure perl file, so it should work easily as long as Glib::Object::Introspection and the introspection data (Gtk-3.0.typelib which might be included in the main gtk3 package) are found.

Before the recent switch to gtk3, gmusicbrowser used gtk2, which was loaded via compiled perl libraries, Gtk2 and others. Those are listed in http://ports.su/perl5 so maybe you want to use that instead, the latest version using gtk2 is in the branch: https://github.com/squentin/gmusicbrowser/tree/v1.1.x

**Comment by ralphee** [comment]
p5-gtk3 is currently being worked on and will be in openbsd ports. Thxs @squentin !
