### ISSUE TITLE
Add support for various mod files

### ISSUE THREAD

**Issue by dmhursh** [squentin/gmusicbrowser#186]
Would it be possible to add support to play and read various mod file formats?  (mod, s3m, xm, it, etc)  I know gstreamer supports them and I suspect some other backends do as well.

Could I get away with using #77 as an example for making changes to add support for a format already supported by GST?  Would GMB work for files with "read-only" meta data?  (I'm fine with it.  I don't want it editing any of my music files.)

**Comment by dmhursh** [comment]
Guess that's a no on just following #77.  Reviewing 03a3713 I'll also need to implement an equivalent to `Tag::OGG`.  I'll look at the 'package Tag::*' files to see if I can reverse engineer what the interface is supposed to be.  Hopefully it's just subs and not globals or an object layout.

**Comment by dmhursh** [comment]
Looks like you hand implemented tag handling in pure perl.  I assume it would be frowned upon if I used a wrapped native library to pick apart mod file headers.

**Comment by squentin** [comment]
I'm thinking about adding support for playing video files (with or without playing the actual video), and I would do that by making their tags read-only as I have no intention of meddling with tags of video formats. So the metadata would not be written in the tag, and only the audio metadata would be read, and maybe video metadata and maybe very generic things like title.
So I guess could add the same kind of support for other audio files like mod files.
If you want to do it yourself the only problem is that I would first have to add a system to determine if a file extension fall into that category (of not being written to tag). I'll take a look.

**Comment by dmhursh** [comment]
I assume you have a rough idea of how you want to implement flagging formats with "writable meta data".  Let me know I'm still learning the organization of the code.  Let me know fit here's a part you'd like me to look at.

I'm not sure if you'd like to handle it globally with something like `$EmbImage_ext_re` or if you want to do something per-backend like `supported_formats()`.  ... or something else.  Idealistically, I like putting the knowledge of the formats in the backends,  but I don't know if that would require too much plumbing work.

**Comment by squentin** [comment]
Sorry for not updating you on this, I went ahead and implemented adding other file formats in read-only mode, it's mostly done. It will use either gstreamer or the mediainfo command to find file metadata.
In the case of mod files, I tested a few different files from modarchive.org and mediainfo can't even tell their duration, gstreamer can, but that's it, no title or anything more. So maybe you'll want to do your own parser (that can use a library).
Anyway, it still needs some polishing, but I really have to work on a way overdue stable release, so it'll be a few more weeks.

**Comment by dmhursh** [comment]
That's great!  Thanks.  I'm assuming it's the recent commits in master.

I have a huge library of mod files.  I'll see what I can do to get at least titles and lengths out of them.  I believe Rhythmbox was able to get the title & length.  Banshee only gets the length and then only when it plays the song.  It won't remember the length.

**Comment by squentin** [comment]
No the recents commits are just tangentially related to this, it's not public yet.

**Comment by dmhursh** [comment]
OK.  I'm looking at libraries, but none of the perl bindings I've found are in debian's old-stable.  I'll see if anything is common in any of the distributions.  Libextractor & mikmod are on CPAN, but they are old.

I suspect it might be safer to just implement something specifically for our purposes so we don't have a dependency disappear in a year.  Fortunately the various mod file formats are all "stable".

**Comment by dmhursh** [comment]
I could maybe build on top of a cli.  It trigger a little bit of a gag reflex, but I suspect it would be pretty portable, at least on Linux.

```console
$ extract -p title -p duration -p mimetype /space/pub/music/mod-old/elsabado.s3m  /space/pub/music/mod-old/timesofl.xm  /space/pub/music/mod-old/techseas.s3m /space/pub/music/mod-old/mars.it /space/pub/music/mod-old/children.mod
Keywords for file /space/pub/music/mod-old/elsabado.s3m:
mimetype - audio/x-s3m
title - El Sabado de Fuego
mimetype - application/octet-stream
duration - 0:03:41.000000000
mimetype - audio/x-mod
title - El Sabado de Fuego
Keywords for file /space/pub/music/mod-old/timesofl.xm:
mimetype - audio/x-xm
mimetype - audio/x-mod
title - Times of Lore
duration - 0:03:45.000000000
mimetype - audio/x-mod
title - Times of Lore
Keywords for file /space/pub/music/mod-old/techseas.s3m:
mimetype - audio/x-s3m
mimetype - application/octet-stream
title - 
duration - 0:04:13.000000000
mimetype - audio/x-mod
Keywords for file /space/pub/music/mod-old/mars.it:
mimetype - audio/x-mod
mimetype - audio/x-mod
title - Mars
duration - 0:04:30.000000000
mimetype - audio/x-mod
title - Mars
Keywords for file /space/pub/music/mod-old/children.mod:
mimetype - audio/x-mod
duration - 0:02:20.000000000
mimetype - audio/x-mod
title - childr@n
```

If libextractor were pure perl, I'd embed it since the license is compatible.  It's just bindings for the native library though.  The duplicates above is a little concerning, but I haven't found them conflicting yet.  I can probably pick a specific parser to use based on the file extension.

**Comment by squentin** [comment]
I've pushed the changes (in both master (gtk3) and v1.1.x (gtk2) branches). You can now add any file that is recognized by gstreamer or mediainfo. You need to enable extensions in Settings->Library->"Select which file types are added", for mod files you'll need to enter the extensions in the text entry.

I haven't made many tests with mod files, but as I said earlier I think you won't get the title or other metadata beside its length. Though you can of course set it manually (it won't be written in the file, but kept it gmb's db).

If you want to get more metadata you can write you own parser, just look at how the mediainfo one works as it's rather simple, unlike the gstreamer one. And you'll need to add a line in gmusicbrowser_tags.pm at the top of the file in %FORMATS like this:
`mod	=> {module=>'Tag::YourModuleName',		format=> 'mod',		tags=>'vorbis',				ro=>1, },`
- you'll need to copy it for each extension like the %Alias_ext thing does or add the aliases in %Alias_ext
- the "format" is optional, it fallbacks to using $info->{audio_format}
- tags=>'vorbis' means you'll pretend to be a vorbis tag like the mediainfo/gstreamer ones do (it's the simplest tags)
- ro=>1 means read-only, otherwise you'd need to support writing tags which would be much more complicated

**Comment by dmhursh** [comment]
Thanks!  I've tested the gtk2 branch on debian, it plays several files.  I was able to add them using the `Select which file types are added..` option in the Library settings, as you said.  It does not load metadata which is expected.  I'll work on writing something to read at least titles & lengths.

I'm tempted to try to pull in IT comments and maybe sample / instrument lists since comments are often hidden there.  But I'll need to make sure it doesn't clutter up gmb's database.

Thanks for you work & help.  On a side note, I just update to debian 10 and this makes it so I can hear my entire library.  I was worried.  The flexibility on the UI, the sort functionality & the behavior of the tray icon are really perfect.  The speed at scanning the library (12,106 songs plus other garbage) was great.

**Comment by dmhursh** [comment]
Just a follow up.  I wasn't as productive over the Christmas break as I had hoped, but I've got a basic library in perl for reading at least the titles for several mod file formats.  In some formats I was able to pick out an artist or comment/message too.  So far I've just gone for low hanging fruit.  I only read the values in the base header of the file.  I don't follow indirection to find other data.

I have a basic test case I use to drive the library for now.  It
- downloads known sample mod files off the internet and validates them against expected sizes and MD5s
- checks the happy path for reading the supported fields from each supported format

  When opening a file to read metadata, the library does validation of "magic numbers" in every format except for the original *.mod format.  It turns out the most basic format is the hardest to validate.  It has a dubious eye catcher somewhere after an array that varies in size depending on the (sub)format.  It creates a chicken & egg problem.  To locate the eye catcher I have to know the format.  To know the format I have to look at the eye catcher.  For now I trust that a .mod file is a .mod file.  I'll get cleaver later.

I plan to dot he following:
- support for reading a few more formats
- better validation & basic validation of .mod files
- get any basic artist, or message fields that are deeper in than the basic header
- gather arrays of text from sample and instrument lists
- integrate the library into gmb.

**Comment by dmhursh** [comment]
I've been really delinquent here.  It was work related.  I'm picking this back up now.  I've pushed what I have to a fork if you'd like to comment.  When I left it, I had a test case that could read basic metadata from various mod file formats.  I was attempting to get it integrated into gmb but wasn't having any luck getting it to hit my code.

I need to start debugging it again.  I'm not sure if I misunderstood the flow at the time or if it was an issue that the files had already been scanned and were not being re-scanned.  I'll come back with some more specific questions in the coming week, but I'm pushing just in case you want to take a look and my mistake jumps out at you.

https://github.com/dmhursh/gmusicbrowser/tree/modfile_metadata
dmhursh@fd62dfda81d0e0a0d971f50e94b35c3fd35617a4
dmhursh@2960349ce72d1a376d22d2e391496ca33abc6d22

**Comment by dmhursh** [comment]
I'm back at this.  I blew away my `~/.config/gmusicbrowser` to test and I was able to confirm that gmb will read the meta-data with the new code on first read.  I'm attaching a screenshot of the meta-data from the test files.

To test I set "try to add these extensions" to "s3m it xm 669 mod mtm dmf ult ptm mdl" and set the library to the `t/samples/` directory.

Remaining issues at the moment.
- [ ] Once I restore my `~/.config/gmusicbrowser`, can I get it to reread the meta-data of my mod files without losing other info like ratings?
- [ ] fix it so I don't have to set "try to add these extensions"
- [ ]  Remove debug code.
- [ ] Fix the reading of song lengths.  (The song length is found if I test with `v1.1.x`.  I was hoping it would merge in.)
- [ ] Address items from https://github.com/squentin/gmusicbrowser/issues/186#issuecomment-758342624

**Comment by dmhursh** [comment]
I'm starting to look into/for the gst song length code.  I'm open to any pointers or suggestions.

Do I need to add something to block mod support if we aren't using GST?
Should I put the modfile extensions in an optional list like `@ScanExtOther` or `@ScanExtVideo`?

**Comment by dmhursh** [comment]
I have support to read the length in seconds for the supported mod file formats.

I'm a little puzzled why I see an album name of "<Unknown> Foo" if the file has an artist of "Foo".  The album isn't shown in the file's properties window.  I'm guessing that's a feature of gmb to differentiate unknown albums.  As long as it's not a bug I created, I like it.

Now I need to test how I can migrate a pre-modfile-meta library to get it to reread supported meta-data without clobbering user supplies metadata like ratings and labels.

**Comment by dmhursh** [comment]
I should have expected that to be easy.  I just filter & highlight the desired files, right click on one of the selected files and hold shift while clicking "Re-read tags".  Then twiddle thumbs as it reads 8800-ish files.

**Comment by dmhursh** [comment]
I created a draft PR to try to clean up a first merge.  At the moment I hit one bug when using my full library that I need to fix.  I'm covering the details in the PR but it's an issue with mod files potentially have text in any encoding and gmb expecting unicode.  The error messages are like
```
Writing tags in /home/xyz/.config/gmusicbrowser/gmbrc ...
Malformed UTF-8 character: \x8b (unexpected continuation byte 0x8b, with no preceding start byte) in substitution (s///) at ./gmusicbrowser.pl line 2609.
*** unhandled exception in callback:
***   Malformed UTF-8 character (fatal) at ./gmusicbrowser.pl line 2609.
```
I have create a test and find a way to sanitize.

**Comment by dmhursh** [comment]
I believe the unicode is resolved.  Just waiting for feedback now.

**Comment by squentin** [comment]
Looking good.
> Should I put the modfile extensions in an optional list like @ScanExtOther or @ScanExtVideo?

Yes, I'll probably add them in their own list.

I was thinking of putting your code in a plugin, but that would leave the question of what happens to the added files when the plugin is disabled, as it's read-only, the generic metadata readers might handle them well enough, but still it may not be worth the trouble.

>I'm a little puzzled why I see an album name of " Foo" if the file has an artist of "Foo". The album isn't shown in the file's properties window. I'm guessing that's a feature of gmb to differentiate unknown albums. As long as it's not a bug I created, I like it.

Yes, unknown albums with an artist name are put into an "<unknown> ARTISTNAME" album, I vaguely intended to make the string format editable, but I've never done it.

I'll think about it some more, and I'll probably commit it in the coming days. Probably as a single commit in your name too keep the history clean and easy to read, unless you'd prefer a merge (git merge --no-ff) to keep your commit history ?

**Comment by dmhursh** [comment]
That sounds fine.  I could create a `@ScanExtMod` but I'd have to do a little bit of investigation before I could make the matching UI change.  I'm planning to learn the UI anyhow to look at #152.  For what it's worth #69 looks like something I can bite off too.

**Comment by dmhursh** [comment]
Oh want me to do the squash?  Let me know.  I'll mark the PR as being ready.

**Comment by squentin** [comment]
I'm wondering how to call the mod files, as I'm really not into that community.
The wikipedia page for these is named "Module file", so I'm thinking of using Module instead of Mod ?
Current strings:

"Modules files" (as a file type in the "add files or folders dialog")
"Partially supported module files extensions" (in the "select which types are added" dialog, "partially supported" mostly because they are read-only)
Audio format: "IT" or "Impulse Tracker" or "module (IT)" or "module (Impulse Tracker)" or "IT (Impulse Tracker)"

Also, I've noticed you've put "MOD" in the optional "Container format" field, but I'm not sure it's technically true, is it ? My guess is that the different mod file types have a completely different format, or are more variant formats. Though it could be useful to have an easy way to filter all mod file formats.

Any thoughts ?

**Comment by dmhursh** [comment]
I think "Module File" could work.  I've heard "tracker file" since the composition software are normally called trackers.  There's not really a good name.  I think the "scene" that mod files came out of refers to themselves as the "Demo Scene" thought I think a lot of the demos these days may be using mp3s or vorbis files.

For the "sub" formats, it probably enough to use names like "Impulse Tracker", "Scream Tracker", etc.  The `typeVerbose()` method on each class is meant to have a good "long name" of the format.  They are usually named after the main editor/track for the format.

I was treating "Container format" as a way to group them.  The earliest mod files were very dependent on the platform and player software.  It seems MOD became a bit more of a standard and follow ons like were modest changes to the format to add new features or extend limits, but they are different.  Others like DMF totally re-engineering of the format.  In any case, I'm find with changing "Container format" to be specific to each file type.  It's not inaccurate.

**Comment by squentin** [comment]
Committed.
I forgot to port my changes to v1.1.x before pushing, so my changes are in a second commit for this branch.
