### ISSUE TITLE
Feature Request: Rich Presence on Discord

### ISSUE THREAD

**Issue by rdricco** [squentin/gmusicbrowser#188]
Would be great to have Rich Presence Status on Discord like Spotify, this is one of the features I miss from MusicBee.

**Comment by indeedwatson** [comment]
Would love this as well.

**Comment by Viktini** [comment]
It'd be nice to have it as a plugin, but as a workaround, [discordrp-mpris](https://github.com/FichteFoll/discordrp-mpris) should work provided that the MPRIS2 plugin is enabled. It's on the AUR with a systemd service if you use Arch.

It will latch onto any playing MPRIS player automatically, though. But if you _really_ want Rich Presence, it will work with gmusicbrowser just fine.

**Comment by rdricco** [comment]
> It'd be nice to have it as a plugin, but as a workaround, [discordrp-mpris](https://github.com/FichteFoll/discordrp-mpris) should work provided that the MPRIS2 plugin is enabled. It's on the AUR with a systemd service if you use Arch, otherwise it's installable via pip.
> 
> It will latch onto any playing MPRIS player automatically, though. But if you _really_ want Rich Presence, it will work with gmusicbrowser just fine.

I don'r think it is necessary anymore. The MPRIS2 plugin can be a better option, supporting other players too. 
Thank you!
