### ISSUE TITLE
Duplicated Genres in m4a Files

### ISSUE THREAD

**Issue by BeatLink** [squentin/gmusicbrowser#196]
When saving genres to a song with a .m4a extension, genre data is written twice, both in the `genre` tag and in the `com.apple.iTunes:genre` tag resulting in duplication of genres in the interface and when using the $genre variable to rename files and folders:

This is what the genre looks like in the main UI
![image](https://user-images.githubusercontent.com/47278150/104857963-0a1a0100-58ea-11eb-9553-47acc1cb31f5.png)

And using the genre variable in folder and file renaming results in this:

![image](https://user-images.githubusercontent.com/47278150/104857987-2fa70a80-58ea-11eb-8cc3-5e7acb9f6508.png)

**Comment by squentin** [comment]
Thanks for reporting this. I fixed it by removing duplicated values when reading the tags, which it should have done anyway.

Though I don't remember at all, writing to both the genre and com.apple.iTunes:genre tag looks very deliberate so I guess I had a reason to do it.

**Comment by BeatLink** [comment]
No problem at all!

**Comment by holybladder** [comment]
This still seems to be the case in 1.1.99.1?

**Comment by squentin** [comment]
Yes, because I still haven't released a new version. Sorry. You can use the git version in the meantime.

**Comment by holybladder** [comment]
> Yes, because I still haven't released a new version. Sorry. You can use the git version in the meantime.

Oh, I see - I actually thought I was working from a daily but it looks like that PPA doesn't support Ubuntu 20.04 - my confusion :) I'll compile, thank you for the update.

**Comment by BeatLink** [comment]
Alternatively, the version on flathub is built from git

**Comment by holybladder** [comment]
> Alternatively, the version on flathub is built from git

Thank you :) Managed to compile it from git, all sorted.
