### ISSUE TITLE
Album Cover does not appear in Mint 20.1 Cinnamon Sound/Player applet

### ISSUE THREAD

**Issue by Oldbwl** [squentin/gmusicbrowser#198]
Although the Gmusicbrowser native applet and player show the front cover, the same image should appear in the taskbar sound applet. This issue is exists on both my machines. I suspect a gtk2 perl file is missing? No reports appear in terminal if the program is started from there.
![Screenshot from 2021-01-23 18-28-00](https://user-images.githubusercontent.com/6871305/105610729-033b3480-5da9-11eb-8fe5-a0e64d6a3e63.jpg)

**Comment by germun** [comment]
Same behavior in Manjaro (KDE 5.20), but maybe is a problem with the AUR package

![Screenshot_20210125_201125](https://user-images.githubusercontent.com/962945/105751352-2ea75600-5f46-11eb-8703-bd1d23e14cf4.png)

**Comment by squentin** [comment]
I'll have to install cinnamon to test it, but can you check first with that command:
`dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.gmusicbrowser /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'`

It will print the current song metadata that is sent via mpris2 to external programs (gmb's native applet doesn't use that), it should list a mpris:artUrl entry containing a local url to the cover file, check if the entry is there and if there is a picture at this url.

**Comment by squentin** [comment]
Ok, it seems there was a problem with an earlier change and it the special case with embedded pictures isn't triggered anymore, I'll look into it.

**Comment by squentin** [comment]
This commit (6db4bc3c5c0c274 for gtk3 version, 6c34b044a627 for gtk2) should fix it, can you confirm ?

**Comment by Oldbwl** [comment]
I tried the commit for gtk3, I can confirm that it worked just fine.

**Comment by Oldbwl** [comment]
Thank you for the effort you make
