### ISSUE TITLE
Bug: tagging oggs w/ faulty headers might corrupt the file!

### ISSUE THREAD

**Issue by DeusIX** [squentin/gmusicbrowser#200]
If I tag oggs with faulty headers the entire file gets truncated into a 4KiB file!

I have tested it with few files:
- Flac, OK
- Ogg (good headers), OK
- Ogg (bad headers), File corruption

**gmp**
Version: gmp-master downloaded: 26.01.2021
Applied patch from: https://github.com/squentin/gmusicbrowser/issues/185

**Example:**

Using oggz-validate -tool to check the validity of the file:
```
$ oggz-validate 19.ogg 
19.ogg: Error:
serialno 1947694221: Terminal header page has non-zero granulepos
serialno 1947694221: Terminal header page contains non-header segment
```

gmp launched from terminal and it shows this:
```
must recompute crc for the whole file, this may take a while (install Digest::CRC to make it fast) ...
replacing old file with new file.
file truncated or corrupted.
Illegal division by zero at /home/me/soft/gmusicbrowser-master/oggheader.pm line 157.
Can't read tags for /home/me/Music/ogg/Attack Rate/19.ogg
```

**Comment by squentin** [comment]
Can you send me (squentin@gmail.com) one ogg file with faulty headers ?

**Comment by squentin** [comment]
Thanks, I've made some changes (8f84c7cd552ad / 5e8fa61e7e3), it should now fail gracefully and leave the file untouched. Although the error is not reported in the gui for now.
