### ISSUE TITLE
Bug: Deleting Song does not automatically remove it from the library

### ISSUE THREAD

**Issue by BeatLink** [squentin/gmusicbrowser#202]

**Comment by squentin** [comment]
Do you mean deleting it from outside gmb ? If yes that's a feature request of watching changes in folders/files.
If not it's a bug, but you'll have to give more details because it should work.

**Comment by BeatLink** [comment]
Its the latter case. Deleting a song from gmusicbrowser's UI does not automatically remove it from the library. It will remain, however clicking on it will say "Resource not found"

**Comment by squentin** [comment]
I've just checked the code, after file deletion the song is added to the list of songs to check, which is not really necessary. So if gmb is currently checking a long list of songs, it could take a while before it reaches that song. Maybe I could make it more direct.

**Comment by BeatLink** [comment]
Yeah!

**Comment by squentin** [comment]
I've made it remove the song directly (b920e062a809f / 85e3f776c1403a), can you confirm it was the problem ?

**Comment by BeatLink** [comment]
Checking it now!
