### ISSUE TITLE
use mpg123 instead of mpg321? mpg321 appears not actively maintained

### ISSUE THREAD

**Issue by MountainX** [squentin/gmusicbrowser#218]
Can GMB use mpg123 instead of mpg321? 

I ask because I am not able to build the mpg321 package for Arch:
[AUR (en) - mpg321](https://aur.archlinux.org/packages/mpg321/ "AUR (en) - mpg321")

Also, mpg123 has a new release on 2021-09-06 17:26 UTC, while mpg321 was last updated 2012-03-25.

The license is no longer an issue:

[mpg123 - Wikipedia](https://en.wikipedia.org/wiki/Mpg123 "mpg123 - Wikipedia")

> In 2006, a new maintainer started work towards the release of a new official mpg123 package. After several security rollup releases in the 0.6.x series, version 1.0 was released in 2007 under the LGPLv2.1

**Comment by MountainX** [comment]
I added this issue because of this message during installation:

```
( 9/28) installing gmusicbrowser-git                                                             [#########################################################] 100%
Optional dependencies for gmusicbrowser-git
    alsa-utils: enables the ALSA backend [installed]
    flac123: flac support for the ALSA backend
    mpg321: mp3 support for the ALSA backend
    vorbis-tools: vorbis support for the ALSA backend
    mplayer: enables the mplayer backend
    mpv: enables the mpv backend [installed]
    gst-plugins-base: vorbis support [installed]
    gst-plugins-good: flac support [installed]
    gst-plugins-ugly: mp3 support
    libappindicator-gtk3: tray icon support [installed]
    webkit2gtk: alternative web-based plugin support [installed]
    libwnck3: titlebar plugin support
    perl-html-parser: support for accented characters in lyrics plugin [installed]
    libnotify: support for notify plugin [installed]
```

As you see, it says "mpg321" explicitly there. However, I realize now that the problem is the Arch Linux PKGBUILD file, not the application.

[PKGBUILD - aur.git - AUR Package Repositories](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gmusicbrowser-git "PKGBUILD - aur.git - AUR Package Repositories")

This PKGBUILD has the wrong optdepends defined, apparently.

**Comment by squentin** [comment]
Yes both mpg123 and mpg321 should work.
Though to be honest I rarely test the 123 commands, I recommend using either gstreamer or mpv/mplayer, the main reason the 123 commands are there is because I started with them.

**Comment by MountainX** [comment]
> Yes both mpg123 and mpg321 should work.
> Though to be honest I rarely test the 123 commands, I recommend using either gstreamer or mpv/mplayer, the main reason the 123 commands are there is because I started with them.

Thank you. I wondered what was the best. I will stick with gstreamer. We can close this issue now.
