### ISSUE TITLE
running latest code from git fails: Attempt to reload HTML/Entities.pm aborted.

### ISSUE THREAD

**Issue by MountainX** [squentin/gmusicbrowser#219]
I was able to install and run [ gmusicbrowser 1.1.16-1](https://aur.archlinux.org/packages/gmusicbrowser "AUR (en) - gmusicbrowser")

However, then I tried installing the version from git:
[gmusicbrowser-git 1.1.99](https://aur.archlinux.org/packages/gmusicbrowser-git/ "AUR (en) - gmusicbrowser-git")

There were no errors during installation. I have all the required dependencies and all the optional ones except mpg321 (for which I opened a separate issue).

Here are the error messages I'm seeing:

    $ gmusicbrowser 
    Attempt to reload HTML/Entities.pm aborted.
    Compilation failed in require at /usr/bin/../share/gmusicbrowser/generic_metadata_reader_mediainfo.pm line 57.
    BEGIN failed--compilation aborted at /usr/bin/../share/gmusicbrowser/generic_metadata_reader_mediainfo.pm line 57.
    Compilation failed in require at /usr/bin/../share/gmusicbrowser/gmusicbrowser_tags.pm line 18.
    BEGIN failed--compilation aborted at /usr/bin/../share/gmusicbrowser/gmusicbrowser_tags.pm line 19.
    Compilation failed in require at /usr/bin/gmusicbrowser line 535.
    BEGIN failed--compilation aborted at /usr/bin/gmusicbrowser line 561.

I tried this as well, even though I don't understand Perl. I thought it might help you.

    $ perl -d /usr/bin/gmusicbrowser

    Loading DB routines from perl5db.pl version 1.60
    Editor support available.

    Enter h or 'h h' for help, or 'man perldebug' for more help.

    Attempt to reload HTML/Entities.pm aborted.
    Compilation failed in require at /usr/bin/../share/gmusicbrowser/generic_metadata_reader_mediainfo.pm line 57.
    at /usr/bin/../share/gmusicbrowser/generic_metadata_reader_mediainfo.pm line 57.
            Tag::Generic::Mediainfo::BEGIN() called at /usr/bin/../share/gmusicbrowser/generic_metadata_reader_mediainfo.pm line 57
            eval {...} called at /usr/bin/../share/gmusicbrowser/generic_metadata_reader_mediainfo.pm line 57
            require generic_metadata_reader_mediainfo.pm called at /usr/bin/../share/gmusicbrowser/gmusicbrowser_tags.pm line 18
            main::BEGIN() called at /usr/bin/../share/gmusicbrowser/generic_metadata_reader_mediainfo.pm line 57
            eval {...} called at /usr/bin/../share/gmusicbrowser/generic_metadata_reader_mediainfo.pm line 57
            require gmusicbrowser_tags.pm called at /usr/bin/gmusicbrowser line 535
            main::BEGIN() called at /usr/bin/../share/gmusicbrowser/generic_metadata_reader_mediainfo.pm line 57
            eval {...} called at /usr/bin/../share/gmusicbrowser/generic_metadata_reader_mediainfo.pm line 57
    BEGIN failed--compilation aborted at /usr/bin/../share/gmusicbrowser/generic_metadata_reader_mediainfo.pm line 57.
    at /usr/bin/../share/gmusicbrowser/generic_metadata_reader_mediainfo.pm line 57.
            require generic_metadata_reader_mediainfo.pm called at /usr/bin/../share/gmusicbrowser/gmusicbrowser_tags.pm line 18
            main::BEGIN() called at /usr/bin/../share/gmusicbrowser/generic_metadata_reader_mediainfo.pm line 57
            eval {...} called at /usr/bin/../share/gmusicbrowser/generic_metadata_reader_mediainfo.pm line 57
            require gmusicbrowser_tags.pm called at /usr/bin/gmusicbrowser line 535
            main::BEGIN() called at /usr/bin/../share/gmusicbrowser/generic_metadata_reader_mediainfo.pm line 57
            eval {...} called at /usr/bin/../share/gmusicbrowser/generic_metadata_reader_mediainfo.pm line 57
    Compilation failed in require at /usr/bin/../share/gmusicbrowser/gmusicbrowser_tags.pm line 18.
    at /usr/bin/../share/gmusicbrowser/gmusicbrowser_tags.pm line 18.
            main::BEGIN() called at /usr/bin/../share/gmusicbrowser/gmusicbrowser_tags.pm line 19
            eval {...} called at /usr/bin/../share/gmusicbrowser/gmusicbrowser_tags.pm line 19
            require gmusicbrowser_tags.pm called at /usr/bin/gmusicbrowser line 535
            main::BEGIN() called at /usr/bin/../share/gmusicbrowser/gmusicbrowser_tags.pm line 19
            eval {...} called at /usr/bin/../share/gmusicbrowser/gmusicbrowser_tags.pm line 19
    BEGIN failed--compilation aborted at /usr/bin/../share/gmusicbrowser/gmusicbrowser_tags.pm line 19.
    at /usr/bin/../share/gmusicbrowser/gmusicbrowser_tags.pm line 19.
            require gmusicbrowser_tags.pm called at /usr/bin/gmusicbrowser line 535
            main::BEGIN() called at /usr/bin/../share/gmusicbrowser/gmusicbrowser_tags.pm line 19
            eval {...} called at /usr/bin/../share/gmusicbrowser/gmusicbrowser_tags.pm line 19
    Compilation failed in require at /usr/bin/gmusicbrowser line 535.
    at /usr/bin/gmusicbrowser line 535.
            main::BEGIN() called at /usr/bin/gmusicbrowser line 561
            eval {...} called at /usr/bin/gmusicbrowser line 561
    BEGIN failed--compilation aborted at /usr/bin/gmusicbrowser line 561.
    at /usr/bin/gmusicbrowser line 561.
    Debugged program terminated.  Use q to quit or R to restart,
    use o inhibit_exit to avoid stopping after program termination,
    h q, h R or h o to get additional info.
      DB<1>

I am running Arch Linux. It is fully updated.

**Comment by squentin** [comment]
Can you check if you have HTML::Entities ?
You can do so with this:  `perl -e 'use HTML::Entities;'`  it will say nothing if found.
It's not in the dependencies of the arch package because it was optional, but it's kind of required by mistake in the new file generic_metadata_reader_mediainfo.pm, although it should be set as recommended or required.

**Comment by MountainX** [comment]
This is resolved. Thank you for your helpful reply. There was nothing wrong with GMB or the Arch package. It was my system, but your help allowed me to solve it.
