### ISSUE TITLE
How to change top level music path and keep all information (last played, etc.)?

### ISSUE THREAD

**Issue by MountainX** [squentin/gmusicbrowser#224]
Hello. Thanks again for your continuing work on this fantastic music player!

I moved all my music to my home server on my LAN. The new location is mounted as an NFS share now. (The name of the mount point is good now and I don't want to rename it.)

I want to point GMB to the new location while not losing any information. 

When I tried simply changing the settings for Library > Folders to search for new songs, GMB found all my music, but all songs have a "Last Played" value of "never" and my Labels all point to the old location.

What is the correct way to change the location of my library without losing any information?

**Comment by skorasaurus** [comment]
As a fellow user; I would search and replace the file path(s) in your gmbrc file which contains all of the settings of gmusicbrowser configuration. 

I have not tested this to verify that it would work (make a back up first!)

**Comment by MountainX** [comment]
> I have not tested this to verify that it would work (make a back up first!)

I did it and it works fine. Thanks.
