### ISSUE TITLE
whishlist: add wma support

### ISSUE THREAD

**Issue by yennor** [squentin/gmusicbrowser#70]
1% of my playlist  consists of wma files. Would be great if I could play them too :-).
It seems like gstreamer and mplayer would support it...

**Comment by squentin** [comment]
Sorry, I haven't wrote a wma parser BUT, in case you still care, you can now (git version, in both master (gtk3) and v1.1.x (gtk2) branches) add any format recognized by gstreamer or mediainfo, though they are added in read-only mode: any change to the metadata you make is only changed within gmb. It is disabled by default you need to enable extensions in Settings->Library->"Select which file types are added".
