### ISSUE TITLE
Application icon is too small to be used in the software center

### ISSUE THREAD

**Issue by remicollet** [squentin/gmusicbrowser#95]
Related to Gnome Software Center and appdata.

See : https://bugzilla.redhat.com/show_bug.cgi?id=1157533

    Currently a 32x32 icon has to be padded with 16 pixels of whitespace on all 4 edges,
    and *also* has to be scaled x2 to match other UI elements on HiDPI screens.

**Comment by squentin** [comment]
I've just changed the icon to a svg icon (and png of various sizes made from the svg). (commit 596b76b7b4)
I think that fixes this bug (sorry it took so long), let me know if there are any problems

(btw I'll make a new release soon, probably in the coming week)
